### ISSUE TITLE
[REQUEST] Add Github Templates

### ISSUE THREAD

**Issue by bhavik2936** [bhavik2936/speed-reader#12]
## Description
Add Github templates to the repository. Below mentioned templates can be duplicated from existing repo [dot-files](https://github.com/bhavik2936/dot-files).

- [ ] Issue Templates
- [ ] Pull Request Template
  - Create `dot-files`' PR template inside `.github` directory, including **Screenshots** section. And remove from _root-level_.
- [ ] Code of Conduct

**Comment by swetha-h** [comment]
Can I take up this issue?

**Comment by bhavik2936** [comment]
Sure, Assigning it to you.
