### ISSUE TITLE
[REQUEST] Remove JSX Logic

### ISSUE THREAD

**Issue by bhavik2936** [bhavik2936/speed-reader#14]
## Description
Remove JSX logic, as **JSX** is not a requirement for using **React**.

## Expected Solution
Remove configuration for `jsx` and convert existing `.jsx` files to `.js`.

## Additional Context
Remove `jsx` configuration from `webpack.config.js`
  - Remove compilation of `.jsx` files for **babel**
  - Remove resolving `.jsx` extension files

Convert extension of files from `.jsx` to `.js`.

**Comment by janmesh799** [comment]
hey bhavik,
i can take this issue to work on

**Comment by tanishq-singh-2301** [comment]
!Assign

**Comment by janmesh799** [comment]
assign me

**Comment by janmesh799** [comment]
made PR regarding the issue
